services:
  - type: web
    name: blood-money-board-app
    env: docker
    dockerfilePath: ./Dockerfile

    
  - type: cron
    name: keep-alive
    env: shell
    schedule: "*/14 * * * *"   #every 14 minutes to prevent render´s autosleep
    buildCommand: echo "Pinging main app"
    startCommand: curl http://blood-money-board-app:10000/health    #uses render´s default port 10000